app1/urls.py
from django.conf.urls import url, path
from . import views

urlpatterns = [
]

my_story4/urls.py
from django.contrib import admin
from app1.views import home as page1
from app1.views import education as page2
from app1.views import experience as page3
from app1.views import contact as page4
from django.urls import path, include
from django.urls import re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('schedule.urls', 'schedule'), namespace='schedule')),
    re_path(r'^home', page1, name="home"),
    re_path(r'^$', page1, name="home"),  
 	re_path(r'^education', page2, name="education"),
 	re_path(r'^experience', page3, name="experience"),
 	re_path(r'^contact', page4, name="contact"),
]

schedule/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('addproject/', views.addproject, name='addproject'),
	path('saveproject/', views.saveproject, name='saveproject'),
	path('deleteproject/', views.deleteproject, name='deleteproject')
]

app1/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime, timedelta

# Create your models here.
class Project(models.Model):
	kategori = models.CharField(max_length=200)
	tempat = models.CharField(max_length=200)
	namakegiatan = models.TextField()
	date = models.DateField(default=date.today)
	time = models.TimeField(auto_now=False, auto_now_add=False)

app1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

def home(request):
	return render(request, 'index_lab1.html')

def education(request):
	return render(request, 'education.html')

def experience(request):
	return render(request, 'experience.html')

def contact(request):
	return render(request, 'contact.html')

schedule/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .schedule import Add_Project_Form
from .models import Project

response = {}

# Create your views here.
def index(request):
    project = Project.objects.all()
    response['project'] = project

    html = 'index_lab1.html'
    return render(request, html, response)

def addproject(request):
    response['title'] = 'Add Project'
    response['addproject_form'] = Add_Project_Form
    html = 'addproject.html'
    return render(request, html, response)

def saveproject(request):
    form = Add_Project_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['kategori'] = request.POST['kategori']
        response['tempat'] = request.POST['tempat']
        response['namakegiatan'] = request.POST['namakegiatan']
        response['date'] = request.POST.get('date')
        response['time'] = request.POST['time']
        project = Project(kategori=response['kategori'], 
            tempat=response['tempat'],namakegiatan=response['namakegiatan'],date=response['date'],time=response['time'])
        project.save()

        project = Project.objects.all()
        response['project'] = project
        html = 'form_result.html'
        return render(request, html, response)
    else:
        html = 'form_result.html'
        return render(request, html, response)

def deleteproject(request):
    project = Project.objects.filter().delete()
    response['project'] = project
    html = 'form_result.html'
    return render(request, html, response)

app1/templates/contact.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>

	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% include "navbar.html" %}
	{% include "socialbar.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<div class="contactform" id="fourthpage">
		<section id="contact">
			<div class="section-content">
				<h1 class="section-header" style="font-style: italic;">Thank You for Visiting Me!</span></h1>
			</div>
			<div class="contact-section">
			<div class="container">
				<form>
					<div class="row">
					<div class="col-md-6 form-line">
			  			<div class="form-group">
			  				<label for="exampleInputUsername">Your name</label>
					    	<input type="text" class="form-control" id="" placeholder=" Enter Name">
				  		</div>
				  		<div class="form-group">
					    	<label for="exampleInputEmail">Email Address</label>
					    	<input type="email" class="form-control" id="exampleInputEmail" placeholder=" Enter Email id">
					  	</div>	
					  	<div class="form-group">
					    	<label for="telephone">Mobile No.</label>
					    	<input type="tel" class="form-control" id="telephone" placeholder=" Enter 10-digit mobile no.">
			  			</div>
			  		</div>
			  		<div class="col-md-6">
			  			<div class="form-group">
			  				<label for ="description"> Date</label>
			  				<br>
			  			 	<input type="Date" name="date">
			  			</div>
			  			<div class="form-group">
			  				<label for ="description"> Message</label>
			  			 	<textarea  class="form-control" id="description" placeholder="Enter Your Message"></textarea>
			  			</div>
			  			<div>
			  				<button type="button" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i>  Submit</button>
			  			</div>			  			
					</div>
					</div>
				</form>
			</div>
		</section>
	</div>

</body>
</html>

app1/templates/education.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% include "navbar.html" %}
	{% include "socialbar.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<!-- EDUCATION -->

	<div class="page2" id="secondpage">

			<div class="container mt-5 mb-5">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				<h4>
					<center>
					<img src="https://upload.wikimedia.org/wikipedia/commons/e/e8/Education%2C_Studying%2C_University%2C_Alumni_-_icon.png" width="200">
					</center>
				</h4>
				<ul class="timeline">
					<li>
						<a>Elementary School</a>
						<a class="float-right">2005</a>
						<p>SDS YBBSU Balikpapan <br>SDN Sukabumi Selatan 03 pagi</p>
					</li>
					<li>
						<a>Secondary School</a>
						<a class="float-right">2011</a>
						<p>SMPN 19 Jakarta<br>SMPN 12 Surabaya<br>SMPN 7 Medan</p>
					</li>
					<li>
						<a>High School</a>
						<a class="float-right">2014</a>
						<p>SMAN 1 Medan<br>SMAN 70 Jakarta</p>
					</li>
					<li>
						<a>University</a>
						<a class="float-right">2017</a>
						<p>Universitas Indonesia</p>
					</li>
				</ul>
			</div>
		</div>
	</div>

	</div>

</body>
</html>

app1/templates/experience.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% include "navbar.html" %}
	{% include "socialbar.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<div class="page3" id="thirdpage">

		<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="box">
                <div class="box-icon">
                    <span></span>
                </div>
                <div class="info">
                    <h3 class="text-center">SKILL</h3>
                    <p><img src="https://ubisafe.org/images/css-transparent-html-6.png" width="150">
			<img src="https://classes.engineering.wustl.edu/cse231/core/images/2/26/Java.png" width="100">
			<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/2000px-Python.svg.png" width="100">
			<img src="https://mbtskoudsalg.com/images/convert-jpg-to-png-transparent-background-photoshop-2.png" width="100"></p>
                </div>
            </div>
        </div>
        
		        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		            <div class="box">
		                <div class="box-icon">
		                    <span></span>
		                </div>
		                <div class="info">
		                    <h3 class="text-center">EXPERIENCE</h3>
						<h4>2017-2018</h4>
						<p>- Staff Publication of Universiade University of Indonesia<br>- Vice Person in Charge of Venue and Equipment Computers Get Together<br>- Organizing Comittee Vice President of Program and Partnership JECP AIESEC in UI</p>
						<h4>2018-present</h4>
						<p>- Staff of Media Partner UI Art War<br>- Team Member of International Relations iGE AIESEC in UI<br>- Human Resource Development of Seminar COMPFEST X</p>
		                </div>
		            </div>
		        </div>
			</div>
		</div>
	</div>
	</div>

</body>
</html>

app1/templates/index_lab1.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% include "navbar.html" %}
	{% include "socialbar.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>
		<!-- PROFILE -->
		<div class="jumbotron" id="firstpage">
		<center>
	  <h1 class="display-4">Hello!</h1>
	  <img src="https://scontent.fjkt1-1.fna.fbcdn.net/v/t1.0-9/41356489_2086381294729523_8140473243795456000_n.jpg?_nc_cat=0&oh=29be8ffd30f25b2b60eebd4e85dc71f6&oe=5C2EA4FF" width="300">
	  <h2 class="display-4">I'm Falya Aqiela Sekardina</h2>
	  <p class="lead">I am a front-end web developer who wants to know more about Information of Technology, loves to eat, loves to travelling, and socialize with friends.</p>
	  <hr>
		</center>
	</div>

	<!-- EDUCATION -->
	<div class="page2" id="education">
	<div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-timeline2">
                        <div class="timeline">
                            <span class="icon fa fa-globe"></span>
                            <a class="timeline-content">
                                <h3 class="title">2017</h3>
                                <h3 class="title">University</h3>
                                <p class="description">
                                    University Indonesia
                                </p>
                            </a>
                        </div>
                        <div class="timeline">
                            <span class="icon fa fa-rocket"></span>
                            <a class="timeline-content">
                                <h3 class="title">2014</h3>
                                <h3 class="title">High School</h3>
                                <p class="description">
                                    <p>SMAN 1 Medan<br>SMAN 70 Jakarta</p>
                                </p>
                            </a>
                        </div>
                        <div class="timeline">
                            <span class="icon fa fa-briefcase"></span>
                            <a class="timeline-content">
                                <h3 class="title">2011</h3>
                                <h3 class="title">Secondary School</h3>
                                <p class="description">
                                    <p>SMPN 19 Jakarta<br>SMPN 12 Surabaya<br>SMPN 7 Medan</p>
                                </p>
                            </a>
                        </div>
                        <div class="timeline">
                            <span class="icon fa fa-mobile"></span>
                            <a class="timeline-content">
                                <h3 class="title">2005</h3>
                                <h3 class="title">Elementary School</h3>
                                <p class="description">
                                    <p>SDS YBBSU Balikpapan <br>SDN Sukabumi Selatan 03 pagi</p>
                                </p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
	</div>

	<div class="page3" id="experience">

		<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="box">
                <div class="box-icon">
                    <span></span>
                </div>
                <div class="info">
                    <h3 class="text-center">SKILL</h3>
                    <p><img src="https://ubisafe.org/images/css-transparent-html-6.png" width="150">
			<img src="https://classes.engineering.wustl.edu/cse231/core/images/2/26/Java.png" width="100">
			<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/2000px-Python.svg.png" width="100">
			<img src="https://mbtskoudsalg.com/images/convert-jpg-to-png-transparent-background-photoshop-2.png" width="100"></p>
                </div>
            </div>
        </div>
        
		        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		            <div class="box">
		                <div class="box-icon">
		                    <span></span>
		                </div>
		                <div class="info">
		                    <h3 class="text-center">EXPERIENCE</h3>
						<h4>2017-2018</h4>
						<p>- Staff Publication of Universiade University of Indonesia<br>- Vice Person in Charge of Venue and Equipment Computers Get Together<br>- Organizing Comittee Vice President of Program and Partnership JECP AIESEC in UI</p>
						<h4>2018-present</h4>
						<p>- Staff of Media Partner UI Art War<br>- Team Member of International Relations iGE AIESEC in UI<br>- Human Resource Development of Seminar COMPFEST X</p>
		                </div>
		            </div>
		        </div>
			</div>
		</div>
	</div>
	</div>

	<div class="contactform" id="contact">
		<section id="contact">
			<div class="section-content">
				<h1 class="section-header" style="font-style: italic;">Thank You for Visiting Me!</span></h1>
			</div>
			<div class="contact-section">
			<div class="container">
				<form>
					<div class="row">
					<div class="col-md-6 form-line">
			  			<div class="form-group">
			  				<label for="exampleInputUsername">Your name</label>
					    	<input type="text" class="form-control" id="" placeholder=" Enter Name">
				  		</div>
				  		<div class="form-group">
					    	<label for="exampleInputEmail">Email Address</label>
					    	<input type="email" class="form-control" id="exampleInputEmail" placeholder=" Enter Email id">
					  	</div>	
					  	<div class="form-group">
					    	<label for="telephone">Mobile No.</label>
					    	<input type="tel" class="form-control" id="telephone" placeholder=" Enter 10-digit mobile no.">
			  			</div>
			  		</div>
			  		<div class="col-md-6">
			  			<div class="form-group">
			  				<label for ="description"> Date</label>
			  				<br>
			  			 	<input type="Date" name="date">
			  			</div>
			  			<div class="form-group">
			  				<label for ="description"> Message</label>
			  			 	<textarea  class="form-control" id="description" placeholder="Enter Your Message"></textarea>
			  			</div>
			  			<div>
			  				<button type="button" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i>  Submit</button>
			  			</div>			  			
					</div>
					</div>
				</form>
			</div>
		</section>
	</div>



</body>
</html>

app1/templates/navbar.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<div class="navbar fixed-top" id="navbar">
		<span>
			<a href="{% url 'home' %}">HOME</a>
			<a href= "#education">EDUCATION</a>
			<a href="#experience">EXPERIENCE</a>
			<a href="#contact">CHECK THIS!</a>
		</span>
			<a href="{% url 'schedule:saveproject' %}">MY SCHEDULE</a>
	</div>

</body>
</html>

app1/templates/socialbar.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<nav class="social">
          <ul>
              <li><a href="https://www.facebook.com/falyaaqiela.sekardina"><i class="fa fa-facebook"></i><b>Facebook</b></a></li>
              <li><a href="https://twitter.com/falya_sekardina"><i class="fa fa-twitter"></i><b>Twitter</b></a></li>
              <li><a href="https://www.linkedin.com/in/falyasekardina"><i class="fa fa-linkedin"></i><b>LinkedIn</b></a></li>
              <li><a href="https://www.instagram.com/falyasekardina/?hl=en"><i class="fa fa-instagram"></i><b>Instagram</b></a></li>
          </ul>
      </nav>

</body>
</html>

schedule/templates/addproject.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Personal Blog</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% include "navbarproject.html" %}
	{% include "socialbar.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylestory3.css' %}" />


	<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="css/linearicons.css">
			<link rel="stylesheet" href="css/owl.carousel.css">
			<link rel="stylesheet" href="css/font-awesome.min.css">
			<link rel="stylesheet" href="css/nice-select.css">			
			<link rel="stylesheet" href="css/magnific-popup.css">
			<link rel="stylesheet" href="css/bootstrap.css">
			<link rel="stylesheet" href="css/main.css">

	<!-- Mobile Specific Meta -->
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Favicon-->
	 <link rel="shortcut icon" href="img/fav.png">
	  <!-- Author Meta -->
	  <meta name="author" content="colorlib">
	  <!-- Meta Description -->
	  <meta name="description" content="">
	  <!-- Meta Keyword -->
	  <meta name="keywords" content="">
	  <!-- meta character set -->
	  <meta charset="UTF-8">

</head>

<!--HTML -->

<body>

	<div style="background-color: black">
		<section class="resume-section p-3 p-lg-5 flex-column" id="projects">
			<h2 style="color: white">Add Schedule</h2>
	<div class="my-auto">
        <div class="col-sm-12 form-row field-desc">
        	<br>
        	<form id="form" method="POST" action="{% url 'schedule:saveproject' %}">
	        	{% csrf_token %}
	          {{ addproject_form.as_p }}
 
	        	<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
       		</form>
        </div>
    </div>
</section>
</div>


</body>
</html>